import type { Metadata } from "next";

import "./globals.css";



export const metadata: Metadata = {
  title: "TaskBuddy2",
  description: "Generated by bidy",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
